version: '2'

services:
  couchdb:
    image: klaemo/couchdb:2.0.0
    # build: ./
    container_name: push_db
    ports:
      - "5984:5984"
    volumes:
      - ./couchdb_data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=root
